spring:
  application:
    name: eregister-user-service
eureka:
  client:
    enabled: true
    serviceURL:
      defaultZone: http://eregister-discovery-service:8761/eureka
  instance:
    preferIpAddress: true