FROM openjdk:8
ADD eregister-user-service-1.0.0-SNAPSHOT.jar eregister-user-service-1.0.0-SNAPSHOT.jar
RUN mkdir -p /var/log/eregister-user-service
CMD java -jar eregister-user-service-1.0.0-SNAPSHOT.jar
